version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    depends_on:
      - db
    ports:
        - "8000:8000"
    networks:
      - app-network

  db:
    container_name: db_postgres_sdo
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5050:5432"
    volumes:
      - ./app/init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge